[package]
name = "wrix-sandbox"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
displaydoc = { workspace = true }
fs2 = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
wrix-core = { workspace = true }

[lints]
workspace = true
