//! Compile-time prompt templates for the Loom workflow phases.
//!
//! Each template family lives in its own submodule; the `Template` impls are
//! generated by Askama (`#[derive(Template)]`) and validated at build time —
//! a missing context field is a compile error.
//!
//! Agent-generated content (`previous_failure`, `title`, `description`,
//! `existing_tasks`) is wrapped in `<agent-output>...</agent-output>` markers
//! in the template bodies as a best-effort prompt-injection mitigation.
//!
//! # Public Contract
//!
//! `loom-templates` is a public-contract crate. External Rust consumers
//! (e.g. RAG pipelines, domain-specific review tools) compose their own
//! templates from the exposed typed building blocks
//! ([`PinnedContext`], [`PreviousFailure`], [`RunContext`],
//! [`ReviewContext`]) and the `PARTIAL_*` partial-string constants
//! below. Loom's own workflow templates (`plan_*`, `todo_*`, `run`,
//! `review`, `msg`) are internal — consumers compose with the partials
//! and typed contexts, not with the workflow shells.

pub mod msg;
pub mod plan;
pub mod previous_failure;
pub mod review;
pub mod run;
pub mod todo;

pub use msg::{ClarifyBead, ClarifyOption, MsgContext};
pub use plan::{PlanNewContext, PlanUpdateContext};
pub use previous_failure::{
    DriverNoticeCause, PREVIOUS_FAILURE_MAX_LEN, PreviousFailure, ReviewConcernKind,
    STDERR_TAIL_PER_BLOCK, VerifierFailure,
};
pub use review::{ReviewContext, ReviewSource};
pub use run::RunContext;
pub use todo::{TodoNewContext, TodoUpdateContext};

/// Project-overview + style-rules pinning shape, exposed as a typed
/// building block external consumers can embed in their own template
/// contexts to mirror Loom's pinning ergonomics without re-deriving the
/// field names.
///
/// `pinned_context` is the project-overview body (`docs/README.md` by
/// default in Loom's binary); `style_rules` is the style-rules document
/// body (`docs/style-rules.md` by default). Both arrive pre-rendered —
/// the template engine treats them as opaque strings.
#[derive(Debug, Clone)]
pub struct PinnedContext {
    pub pinned_context: String,
    pub style_rules: String,
}

/// `partial/companions_context.md` — list companion paths declared on the spec.
pub const PARTIAL_COMPANIONS_CONTEXT: &str =
    include_str!("../templates/partial/companions_context.md");

/// `partial/context_pinning.md` — pin the project-overview file.
pub const PARTIAL_CONTEXT_PINNING: &str = include_str!("../templates/partial/context_pinning.md");

/// `partial/exit_signals.md` — document the `LOOM_*` exit markers the
/// phase accepts.
pub const PARTIAL_EXIT_SIGNALS: &str = include_str!("../templates/partial/exit_signals.md");

/// `partial/interview_modes.md` — describe the "one by one" / "polish
/// the spec" interview sub-modes.
pub const PARTIAL_INTERVIEW_MODES: &str = include_str!("../templates/partial/interview_modes.md");

/// `partial/invariant_clash.md` — describe the invariant-clash awareness scan.
pub const PARTIAL_INVARIANT_CLASH: &str = include_str!("../templates/partial/invariant_clash.md");

/// `partial/plan_stage_rubric.md` — gate the planning interview on
/// completeness / coherence / invariant-clash.
pub const PARTIAL_PLAN_STAGE_RUBRIC: &str =
    include_str!("../templates/partial/plan_stage_rubric.md");

/// `partial/review_rubric.md` — per-diff review rubric.
pub const PARTIAL_REVIEW_RUBRIC: &str = include_str!("../templates/partial/review_rubric.md");

/// `partial/scratchpad.md` — pin the per-session scratchpad path.
pub const PARTIAL_SCRATCHPAD: &str = include_str!("../templates/partial/scratchpad.md");

/// `partial/sibling_spec_editing.md` — authorize cross-spec edits during
/// a planning session.
pub const PARTIAL_SIBLING_SPEC_EDITING: &str =
    include_str!("../templates/partial/sibling_spec_editing.md");

/// `partial/spec_conventions.md` — pin the spec-conventions document.
pub const PARTIAL_SPEC_CONVENTIONS: &str = include_str!("../templates/partial/spec_conventions.md");

/// `partial/spec_header.md` — render spec label, path, active molecule.
pub const PARTIAL_SPEC_HEADER: &str = include_str!("../templates/partial/spec_header.md");

/// `partial/style_rules.md` — pin the style-rules file.
pub const PARTIAL_STYLE_RULES: &str = include_str!("../templates/partial/style_rules.md");
