//! Compile-time prompt templates for the Loom workflow phases.
//!
//! Each template family lives in its own submodule; the `Template` impls are
//! generated by Askama (`#[derive(Template)]`) and validated at build time —
//! a missing context field is a compile error.
//!
//! Agent-generated content (`previous_failure`, `title`, `description`,
//! `existing_tasks`) is wrapped in `<agent-output>...</agent-output>` markers
//! in the template bodies as a best-effort prompt-injection mitigation.

pub mod check;
pub mod msg;
pub mod plan;
pub mod run;
pub mod todo;
