#!/usr/bin/env bash
# Judge rubrics for beads.md success criteria

test_sync_in_container() {
  judge_files "lib/sandbox/linux/entrypoint.sh" "lib/sandbox/darwin/entrypoint.sh"
  judge_criterion "In the container environment, bd is wired to the host's shared dolt instance via BEADS_DOLT_SERVER_SOCKET (bound to /workspace/.wrix/dolt.sock) with BEADS_DOLT_AUTO_START disabled. Through this socket, bd dolt pull and bd dolt push operate against the host-shared dolt database (remote-to-host sync is a separate, host-side concern). A missing socket is fatal rather than silently falling back to a per-container dolt."
}

test_shellhook_lifecycle_isolation() {
  judge_files "lib/beads/default.nix"
  judge_criterion "On Linux, beads.shellHook starts the dolt container with a lifecycle independent of the caller process's cgroup. PASS if the Linux branch probes for user-systemd availability (e.g. command -v systemd-run combined with systemctl --user is-active dbus.service) and, when available, wraps the beads-dolt start invocation in systemd-run --user --scope (with --collect for transient-scope cleanup), so the container's conmon and descendants land in a transient user scope rather than inheriting the caller's cgroup. When user systemd is unavailable (sandbox container, non-systemd host), the shellHook must fall back to the direct beads-dolt start invocation so those environments continue to work. Both code paths must propagate non-zero exit status from beads-dolt start as a shellHook failure (no fallback to embedded dolt). The Darwin branch needs no equivalent — Apple's container and podman-via-VM already isolate via separate process trees."
}

test_shellhook_fail_loud() {
  judge_files "lib/beads/default.nix"
  judge_criterion "When a beads workspace is detected (\$PWD/.beads/dolt exists), beads.shellHook fails non-zero with a stderr message — and never falls back to an embedded dolt — in both fail-loud branches: (a) the missing-runtime branch, where Darwin requires either 'container' or 'podman' on PATH and Linux requires 'podman' on PATH, and (b) the unreachable-dolt branch in waitAndExport, where dolt must become reachable within the bounded startup budget (Darwin: TCP 127.0.0.1:\$port; Linux: a Unix socket at the beads-dolt-reported path) before the loop gives up. Both branches must emit a stderr diagnostic identifying the failure cause and terminate the shellHook with non-zero status (return 1 / exit 1) instead of leaving BEADS_DOLT_AUTO_START enabled or otherwise permitting bd to silently spawn an embedded dolt."
}

test_workspace_naming_determinism() {
  judge_files "lib/beads/default.nix"
  judge_criterion "The _hash, _name, and _port helpers derive the per-workspace container name and port deterministically from the workspace path so that (a) the same workspace path always yields the same name and the same port across invocations — _hash is a pure function of the path (sha256sum of the path, truncated to 8 hex chars), _name is basename(path)-beads, and _port is 13306 + (hash mod 500), each computed from \$1 (falling back to \$PWD) with no hidden time- or env-dependent inputs — and (b) collision risk between distinct workspace paths is bounded by the sha256 derivation: ports live in a fixed [13306, 13805] window of 500 slots, and the hash-to-port mapping uses sha256 truncation rather than a path-component shortcut, so name collisions require basename collisions and port collisions require sha256-prefix collisions over the 500-slot window rather than being structurally forced by path similarity."
}

test_beadspush_pushes_before_pulls() {
  judge_files "scripts/beads-push"
  judge_criterion "On the happy path, beads-push invokes 'bd dolt push' before any 'bd dolt pull'. PASS if the dolt-sync sequence runs 'bd dolt commit' (best-effort) followed by 'bd dolt push' as the first remote-mutating call, and the 'bd dolt pull' invocation lives only inside a fallback branch that is entered when (and only when) the initial push exited non-zero. The fallback must itself only be triggered for fast-forward / non-fast-forward style rejections (e.g. the script inspects captured push stderr for 'non-fast-forward', 'reject', 'behind', 'out of date', or equivalent patterns); other push failures (network, auth, disk) must propagate the original push exit code without ever calling 'bd dolt pull'. The net effect against an up-to-date remote is that 'bd dolt pull' is never executed, so the session-close run never enters the Dolt merge path."
}

test_beadspush_failloud_on_intent_overwrite() {
  judge_files "scripts/beads-push"
  judge_criterion "On the pull-fallback path, beads-push snapshots local status and labels intent BEFORE running 'bd dolt pull', re-reads the same rows after the pull, and refuses to push when post-pull state diverges from the snapshot. PASS if all of the following hold: (a) the affected-issue set is derived from a Dolt system-table column diff between local HEAD and the remote-tracking branch (queries against dolt_commit_diff_issues and dolt_commit_diff_labels, or the equivalent dolt_diff_* per-table system tables, filtered to rows where status changed or labels were added/removed); (b) the pre-pull snapshot captures both status and the labels set for each affected issue (e.g. via SELECT against issues joined to a GROUP_CONCAT over labels, or equivalent); (c) the same snapshot query runs again after 'bd dolt pull' and the two outputs are compared (diff, equality check, or row-by-row comparison); (d) on any divergence, the script writes the affected issue IDs to stderr and exits non-zero WITHOUT calling 'bd dolt push' a second time; (e) the divergence check covers updates only — insert/delete row collisions are out of scope and need not be handled."
}

test_beadspush_disables_autoexport() {
  judge_files "scripts/beads-push"
  judge_criterion "beads-push disables bd's auto-export hook on every invocation by writing 'bd config set export.auto false' (with stdout suppressed, e.g. '>/dev/null') after workspace context is resolved and BEFORE any 'bd dolt' invocation (including the first 'bd dolt commit' on the dolt-sync path). PASS if all of the following hold: (a) the script contains exactly one such write in the normal execution path (a function called unconditionally by main is acceptable after the refactor); (b) no 'bd dolt' push/pull/commit call can execute before it on the non-LOOM path; (c) the setting is intentionally persistent — there is NO save/restore trap, no later 'bd config set export.auto true', no EXIT/RETURN trap that re-enables auto-export, so the value persisted in .beads/config.yaml carries forward to subsequent bd calls inside and outside beads-push; (d) a one-line comment (per COM-1) explains that the persistence is intentional and/or why the suppression is needed. FAIL if the write is missing, can be skipped on the happy path, is paired with a restore-to-true, or precedes the workspace setup the script relies on."
}

test_beadspush_repairs_host_dolt_remote() {
  judge_files "scripts/beads-push"
  judge_criterion "On non-LOOM host invocations, beads-push repairs a missing or stale Dolt origin remote to the current host checkout's beads worktree remote (file://\$ROOT/.git/beads-worktrees/\$BRANCH/.beads/dolt-remote) before bd dolt sync. PASS if all of the following hold: (a) the repair is explicitly skipped when running in a sandbox/container path, so /workspace is never persisted into shared Beads config; (b) the repair removes/replaces an existing stale origin and adds the host-path origin before any 'bd dolt commit/push/pull'; (c) the repair updates the SQL Dolt remote directly (for example via DOLT_REMOTE) rather than 'bd dolt remote add', so it cannot write or auto-commit sync.remote into .beads/config.yaml; (d) missing beads worktree remote is a no-op so bootstrap/recreate paths still work."
}

test_beadspush_loom_inside_noop() {
  judge_files "scripts/beads-push"
  judge_criterion "When \$LOOM_INSIDE is set, beads-push performs a full no-op before any git or bd operation: after shell setup and function definitions, main's first operation checks \$LOOM_INSIDE and, when non-empty, writes a one-line notice to stderr and exits 0. PASS if all of the following hold: (a) on the \$LOOM_INSIDE path no git command and no bd command (config, dolt commit/push/pull) can execute; (b) on a set \$LOOM_INSIDE the script exits 0 with a single-line stderr notice; (c) the expansion is safe under 'set -u' (e.g. \${LOOM_INSIDE:-}); (d) a comment explains why the loom clone must not push (origin points at the driver workdir, the driver owns publish, a push here races the driver). FAIL if any bd/git call can run before the guard, if it does not exit 0, or if it is missing."
}

test_beadspush_failloud_missing_repo() {
  judge_files "scripts/beads-push"
  judge_criterion "When \$LOOM_INSIDE is unset and 'git rev-parse --show-toplevel' does not resolve a workspace root (ROOT ends up empty), beads-push exits non-zero with an actionable stderr message naming the unresolved repository location — never proceeding with an empty ROOT into a git invocation that prints 'fatal: not a git repository: (null)'. PASS if all of the following hold: (a) immediately after ROOT is assigned from 'git rev-parse --show-toplevel' (and the beads-worktree peel-back case), an explicit guard tests for an empty ROOT (e.g. [[ -z \"\$ROOT\" ]]); (b) on empty ROOT the script writes a one-line stderr message that identifies the unresolved location (e.g. \$PWD) and tells the operator to run inside a workspace checkout, then exits non-zero; (c) the guard sits BEFORE 'WT=\"\$ROOT/...\"' and any later 'cd \"\$WT\"' / worktree git call, so an empty ROOT can never flow into a git invocation; (d) the '|| true' that swallows the rev-parse error carries a comment (per SH-6) explaining the empty-ROOT guard handles the failure. FAIL if the empty-ROOT case falls through to WT setup or any git call, or if the error message is absent/non-actionable."
}

test_beadspush_pre_pull_cleanup_canonical() {
  judge_files "scripts/beads-push"
  judge_criterion "The two leftover-dirt cleanup guards in beads-push — the one that runs before 'git pull --rebase' and the one that runs after the rsync of REMOTE_DIR — both detect a dirty beads worktree using the same surface 'git rebase' itself consults: 'git update-index --refresh' (output discarded; a non-zero exit is expected and tolerated because update-index returns 1 when it flushes stale stat entries, which is the signal the script wants flushed) followed by 'git status --porcelain --untracked-files=normal' (a non-empty result triggers 'git add -A' + 'git commit'). PASS if BOTH guard sites use this canonical sequence. FAIL if either guard still relies on the older 'git diff --quiet || git ls-files --others --exclude-standard' combination, which trusts the index's stat cache and can therefore miss a tracked file whose mtime/size are unchanged but whose content differs — exactly the scenario where the subsequent 'git pull --rebase' aborts with 'You have unstaged changes' after the cleanup believed the tree was clean. FAIL also if the '|| true' tolerance on 'git update-index --refresh' is missing or lacks a comment explaining why the non-zero exit is intentional (per SH-6)."
}

test_beadspush_recovers_orphaned_worktree() {
  judge_files "scripts/beads-push"
  judge_criterion "The beads-branch sync recreates the beads worktree when its directory exists but is no longer a valid git worktree — the canonical orphaned case where '.git/worktrees/<branch>' was pruned or removed, leaving the directory present with a dangling gitdir pointer. PASS if all of the following hold: (a) the recreate guard fires on BOTH the absent directory case AND the present-but-invalid case — e.g. the condition is '[ ! -d \"\$WT\" ] || ! git -C \"\$WT\" rev-parse --is-inside-work-tree' (or an equivalent validity probe), NOT the absent-only '[ ! -d \"\$WT\" ]'; (b) on the invalid case the script prunes the stale worktree registration ('git worktree prune'), removes the directory ('rm -rf \"\$WT\"'), and re-adds the worktree via the existing 'git worktree add' path that rebuilds relative to the current \$ROOT (falling back to 'origin/<branch>' and skipping with a notice when no branch exists); (c) the recovery completes the rest of the beads-branch sync rather than aborting — exiting 0, printing 'beads-push: synced to GitHub', and advancing origin/<branch>; (d) an empty \$ROOT can never reach this path (the upstream empty-ROOT guard already failed loud), so the recreate never emits 'fatal: not a git repository: (null)'. The pointer-fix block (gated on the admin gitdir existing) does NOT satisfy this criterion — it cannot repair a dangling admin directory. FAIL if the guard is absent-only, if the invalid case is not pruned/removed/re-added, or if a dangling worktree aborts the sync."
}

test_beadspush_worktree_recreate_skips_prek() {
  judge_files "scripts/beads-push"
  judge_criterion "Every git invocation in the beads-branch sync section skips prek so the config-less 'beads' branch never aborts the sync with 'No prek.toml … found'. PASS if all of the following hold: (a) 'export PREK_ALLOW_NO_CONFIG=1' is set exactly once near the top of the beads-branch sync section — after the dolt commit/push phase and BEFORE the worktree-recreate guard — so it covers the recreating 'git worktree add' and its post-checkout hook as well as the later update-index/status/pull/commit/push calls; (b) the recreate path therefore completes without the CALLER having pre-set PREK_ALLOW_NO_CONFIG in the environment; (c) the now-redundant per-call 'PREK_ALLOW_NO_CONFIG=1' command prefixes on the git add/commit/pull/push calls are removed, since the single export already covers them; (d) the prek-skip is scoped to the beads-branch sync — the preceding Dolt commit/push phase is unchanged and not wrapped in the bypass. FAIL if 'git worktree add' runs outside the bypass (so a fresh recreate hits 'No prek.toml … found'), if the export is missing, or if the bypass leaks into the dolt-push phase."
}
